Repository RedHatCloudForms/cfme-migration_analytics, pull requests merged in 2019-08, with the labels that each got.

#12 Fix the name of the API controller
  app/controllers/api/red_hat_migration_analytics_controller.rb
  spec/requests/red_hat_migration_analytics_spec.rb
Labels: bug

#11 Filter out any password from the manifest
  app/controllers/api/red_hat_migration_analytics_controller.rb
  spec/requests/red_hat_migration_analytics_spec.rb
Labels: enhancement, ivanchuk/yes

#14 Add Settings.prototype.migration_analytics.enabled flag to disable the feature in a supported way, enable vmdb_plugin
  app/controllers/api/red_hat_migration_analytics_controller.rb
  config/routes.rb
  config/settings.yml
  lib/cfme/migration_analytics/engine.rb
Labels: changelog/no, ivanchuk/yes

#15 Bundle_queue takes targets as [[klass, id]]
  app/controllers/api/red_hat_migration_analytics_controller.rb
  spec/requests/red_hat_migration_analytics_spec.rb
Labels: bug

#18 Allow user to upload a custom manifest
  app/controllers/api/red_hat_migration_analytics_controller.rb
Labels: enhancement

#17 Run inventory bundle action, poll for completion, and display payload path and working download button
  app/controllers/api/red_hat_migration_analytics_controller.rb
  app/javascript/react/screens/App/Analytics/Analytics.scss
  app/javascript/react/screens/App/Analytics/components/EmptyStateWithButton.js
  app/javascript/react/screens/App/Analytics/components/__tests__/EmptyStateWithButton.test.js
  app/javascript/react/screens/App/Analytics/components/__tests__/__snapshots__/EmptyStateWithButton.test.js.snap
  app/javascript/react/screens/App/Analytics/redux/analyticsActions.js
  app/javascript/react/screens/App/Analytics/redux/analyticsReducer.js
  app/javascript/react/screens/App/Analytics/redux/analyticsSelectors.js
  app/javascript/react/screens/App/Analytics/redux/constants.js
  app/javascript/react/screens/App/Analytics/screens/AnalyticsDataCollection/AnalyticsDataCollection.js
  app/javascript/react/screens/App/Analytics/screens/AnalyticsDataCollection/__tests__/AnalyticsDataCollection.test.js
  app/javascript/react/screens/App/Analytics/screens/AnalyticsDataCollection/__tests__/__snapshots__/AnalyticsDataCollection.test.js.snap
  app/javascript/react/screens/App/Analytics/screens/AnalyticsDataCollection/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Analytics/screens/AnalyticsDataCollection/helpers.js
  app/javascript/react/screens/App/Analytics/screens/AnalyticsDataCollection/index.js
  app/javascript/react/screens/App/Analytics/screens/AnalyticsProviderSelection/AnalyticsProviderSelection.js
  app/javascript/react/screens/App/Analytics/screens/AnalyticsSummary/AnalyticsSummary.js
  app/javascript/react/screens/App/Analytics/screens/AnalyticsSummary/components/ProviderRefreshErrors.js
  app/javascript/react/screens/App/Analytics/screens/AnalyticsSummary/components/ReportTaskError.js
  app/javascript/redux/__tests__/__snapshots__/createReducers.test.js.snap
Labels: changelog/no, ivanchuk/yes

#20 Use scp to download generated analytics file
  app/javascript/react/screens/App/Analytics/redux/analyticsSelectors.js
  app/javascript/react/screens/App/Analytics/screens/AnalyticsDataCollection/AnalyticsDataCollection.js
  app/javascript/react/screens/App/Analytics/screens/AnalyticsDataCollection/__tests__/AnalyticsDataCollection.test.js
  app/javascript/react/screens/App/Analytics/screens/AnalyticsDataCollection/__tests__/__snapshots__/AnalyticsDataCollection.test.js.snap
  app/javascript/react/screens/App/Analytics/screens/AnalyticsDataCollection/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Analytics/screens/AnalyticsDataCollection/index.js
Labels: enhancement

#22 Use React.createRef to prevent eslint override, restore commented-out tests
  .jest-setup.js
  app/javascript/react/screens/App/Analytics/screens/AnalyticsDataCollection/AnalyticsDataCollection.js
  app/javascript/react/screens/App/Analytics/screens/AnalyticsDataCollection/__tests__/AnalyticsDataCollection.test.js
  app/javascript/react/screens/App/Analytics/screens/AnalyticsDataCollection/__tests__/__snapshots__/AnalyticsDataCollection.test.js.snap
Labels: changelog/no, ivanchuk/yes

#23 Add unit tests for data collection screen UI code
  app/javascript/common/testReduxHelpers.js
  app/javascript/react/screens/App/Analytics/redux/__tests__/__snapshots__/analyticsReducer.test.js.snap
  app/javascript/react/screens/App/Analytics/redux/__tests__/analyticsActions.test.js
  app/javascript/react/screens/App/Analytics/redux/__tests__/analyticsReducer.test.js
  app/javascript/react/screens/App/Analytics/redux/__tests__/analyticsSelectors.test.js
  app/javascript/react/screens/App/Analytics/screens/AnalyticsDataCollection/__tests__/AnalyticsDataCollection.test.js
  app/javascript/react/screens/App/Analytics/screens/AnalyticsDataCollection/__tests__/__snapshots__/AnalyticsDataCollection.test.js.snap
  app/javascript/react/screens/App/Analytics/screens/AnalyticsDataCollection/__tests__/helpers.test.js
  app/javascript/react/screens/App/Analytics/screens/AnalyticsDataCollection/testHelpers.js
  app/javascript/react/screens/App/Analytics/screens/AnalyticsSummary/testHelpers.js
  app/javascript/redux/__tests__/helpers.test.js
  app/javascript/redux/providers/__tests__/__snapshots__/providersReducer.test.js.snap
  app/javascript/redux/providers/__tests__/providersReducer.test.js
  app/javascript/redux/reports/__tests__/__snapshots__/reportsReducer.test.js.snap
  app/javascript/redux/reports/__tests__/reportsReducer.test.js
Labels: changelog/no, ivanchuk/yes
