Repository RedHatCloudForms/cfme-migration_analytics, pull requests merged in 2020-03, with the labels that each got.

#42 Set enabled to true by default
  config/settings.yml
Labels: ivanchuk/yes

#43 Permanently enable plugin (Remove feature_check mixin and enabled setting)
  app/controllers/api/mixins/feature_check.rb
  app/controllers/api/red_hat_migration_analytics_controller.rb
  app/controllers/api/red_hat_migration_analytics_payload_controller.rb
  config/routes.rb
  config/settings.yml
  lib/cfme/migration_analytics/engine.rb
  spec/requests/red_hat_migration_analytics_payload_spec.rb
  spec/requests/red_hat_migration_analytics_spec.rb
Labels: bz, ivanchuk/yes

#46 Change labels in Update Manifest modal
  app/javascript/react/screens/App/Analytics/components/ManifestUpdateModal.js
Labels: bz, enhancement, ivanchuk/yes

#44 [JANSA] Update source catalog for jansa
  .tx/config
  locale/Cfme_MigrationAnalytics.pot
  locale/en/Cfme_MigrationAnalytics.po
  locale/es/Cfme_MigrationAnalytics.po
  locale/fr/Cfme_MigrationAnalytics.po
  locale/ja/Cfme_MigrationAnalytics.po
  locale/pt_BR/Cfme_MigrationAnalytics.po
  locale/zh_CN/Cfme_MigrationAnalytics.po
Labels: internationalization

#41 [IVANCHUK] Add gettext catalog for ivanchuk branch
  locale/Cfme_MigrationAnalytics.pot
  locale/en/Cfme_MigrationAnalytics.po
  locale/es/Cfme_MigrationAnalytics.po
  locale/fr/Cfme_MigrationAnalytics.po
  locale/ja/Cfme_MigrationAnalytics.po
  locale/pt_BR/Cfme_MigrationAnalytics.po
  locale/zh_CN/Cfme_MigrationAnalytics.po
Labels: internationalization
