Repository RedHatCloudForms/cfme-migration_analytics, pull requests merged in 2020-01, with the labels that each got.

#32 added guest_applications
  config/default-manifest.json
Labels: enhancement, ivanchuk/yes

#28 Implement upload of the manifest.
  app/controllers/api/red_hat_migration_analytics_controller.rb
  config/api.yml
  spec/requests/red_hat_migration_analytics_spec.rb
Labels: bz, enhancement, ivanchuk/yes

#34 Drop host_storages.ems_ref from default manifest to prevent payload collection error
  config/default-manifest.json
Labels: bug

#36 Add modal for uploading/resetting manifest in UI
  app/javascript/react/screens/App/Analytics/Analytics.js
  app/javascript/react/screens/App/Analytics/Analytics.scss
  app/javascript/react/screens/App/Analytics/__tests__/__snapshots__/Analytics.test.js.snap
  app/javascript/react/screens/App/Analytics/components/ManifestUpdateModal.js
  app/javascript/react/screens/App/Analytics/components/ManifestVersion.js
  app/javascript/react/screens/App/Analytics/components/helpers.js
  app/javascript/react/screens/App/Analytics/index.js
  app/javascript/react/screens/App/Analytics/redux/__tests__/__snapshots__/analyticsReducer.test.js.snap
  app/javascript/react/screens/App/Analytics/redux/analyticsActions.js
  app/javascript/react/screens/App/Analytics/redux/analyticsReducer.js
  app/javascript/react/screens/App/Analytics/redux/constants.js
  app/javascript/redux/__tests__/__snapshots__/createReducers.test.js.snap
  package.json
  yarn.lock
Labels: bz, enhancement, ivanchuk/yes, needs-tests
